CREATE TABLE public."Universities" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Country" text NOT NULL,
    "Sites" text NOT NULL
);

ALTER TABLE public."Universities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Universities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


